package com.travelapp.config

import com.travelapp.sdk.config.CornerType
import com.travelapp.sdk.config.AppTabs
import com.travelapp.sdk.config.EnabledInfoItems
import com.travelapp.sdk.config.IconsType
        
/**
* Do not modify! Auto generated by 'parseConfig' task
*/
object WhiteLabelConf {

    const val host: String = ""
    
    const val apiKey: String = "40aa1345ae7f6e55e72568b27207f3e2"

    const val email: String = "support@mobile-testing.ru"

    const val appVerison: String = "1.5"

    const val appId: String = "ru.aviabilety.deshevo"
    
    val marker: Int = 154286
    
    val clientDeviceHost: String = "android.ru.aviabilety.deshevo"

    val flightsTabEnabled: Boolean = true
    
    val hotelsTabEnabled: Boolean = true

    const val sharingLink: String = ""

    const val handlingLink: String = ""

    const val appsflyerDevKey: String = ""

    object Style {
        val cornerType: CornerType = CornerType.getByName("round")
        val iconsType: IconsType = IconsType.getByName("tint")
    }
    
    object InfoConfig {
        val enabledItems: Set<EnabledInfoItems> = setOf<EnabledInfoItems?>(
            EnabledInfoItems.getByName("favorites"), EnabledInfoItems.getByName("about_app"), EnabledInfoItems.getByName("rate_app"), EnabledInfoItems.getByName("share_app")
        ).filterNotNull().toSet()
    }

    object Advertising {
        const val appodealApiKey: String = ""

        object Placements {
            const val airTicketPlacementInterstitial: String = ""

            const val airTicketPlacementBanner: String = ""

            const val hotelsPlacementInterstitial: String = ""

            const val hotelsPlacementBanner: String = ""

        }
    }




    
    

    
}